GeekPlanner/authapp/urls.py
"""
Module for authapp URLs.
"""
from django.urls import path, re_path
from django.views.generic.base import TemplateView

from django_registration.backends.activation.views import ActivationView, RegistrationView

from .views import LoginView, LogoutView, UserUpdateView,\
                    RegistrationClosedView, RegistrationCompleteView
from .forms import UserRegistrationForm


app_name = 'authapp'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'edit/',
        UserUpdateView.as_view(),
        name='edit'
    ),
    # Django-registration urls
    path(
        'register/',
        RegistrationView.as_view(
            form_class=UserRegistrationForm
        ),
        name='django_registration_register'
    ),
    path(
        'register/complete/',
        RegistrationCompleteView.as_view(),
        name='django_registration_complete'
    ),
    path(
        'register/closed/',
        RegistrationClosedView.as_view(),
        name='django_registration_closed'
    ),
    path(
        'activate/complete/',
        TemplateView.as_view(
            template_name='django_registration/activation_complete.html'
        ),
        name='django_registration_activation_complete'
    ),
    re_path(
        r'^activate/(?P<activation_key>[-:\w]+)/$',
        ActivationView.as_view(),
        name='django_registration_activate'
    ),
]

GeekPlanner/plannerapp/urls.py
"""
Module for plannerapp URLs.
"""
from django.urls import path

import plannerapp.views as plannerapp


app_name = 'plannerapp'

urlpatterns = [
    path(
        'projects/',
        plannerapp.ProjectListView.as_view(),
        name='projects'
    ),
    path(
        'create_project/',
        plannerapp.ProjectCreateView.as_view(),
        name='create_project'
    ),
    path(
        'update_project/<int:pk>/',
        plannerapp.ProjectUpdateView.as_view(),
        name='update_project'
    ),
    path(
        'delete_project/<int:pk>/',
        plannerapp.ProjectDeleteView.as_view(),
        name='delete_project'
    ),
    path(
        'project_details/<int:pk>/',
        plannerapp.ProjectDetailView.as_view(),
        name='project_details'
    ),
    path(
        'create_card/project/<int:project_pk>/category/<int:category_pk>/',
        plannerapp.CardCreateView.as_view(),
        name='create_card'
    ),
    path(
        'delete_card/<int:pk>/project/<int:project_pk>/',
        plannerapp.CardDeleteView.as_view(),
        name='delete_card'
    ),
    path(
        'update_card/<int:pk>/project/<int:project_pk>/',
        plannerapp.CardUpdateView.as_view(),
        name='update_card'
    ),
    path(
        'create_category/<int:pk>/project/<int:project_pk>/',
        plannerapp.CategoryCreateView.as_view(),
        name='create_category',
    ),
    # path(
    #     'update_category/<int:pk>/project/<int:project_pk>/',
    #     plannerapp.CategoryUpdateView.as_view(),
    #     name='update_category',
    # ),
    path(
        'delete_category/<int:pk>/project/<int:project_pk>/',
        plannerapp.CategoryDeleteView.as_view(),
        name='delete_category',
    )
]

GeekPlanner/plannerapp/models.py
"""
Module for plannerapp models.
"""
import os
import functools

from django.db import models
from django.conf import settings

from authapp.models import User


def get_default_category_pk(name):
    """
    Gets default category PK
    :param name: name of category
    :return:
    """
    return Category.objects.get_or_create(name=name)[0].pk


class Project(models.Model):
    """
    Project represents a separated functional area, where users collaborate, work with cards
    and boards.
    """
    # Project name
    title = models.CharField(
        verbose_name='title',
        max_length=64
    )
    # Short description of what project is about
    description = models.TextField(
        verbose_name='description',
        max_length=256,
        blank=True
    )
    # Creator of the project
    owner = models.ForeignKey(
        User,
        verbose_name='owner',
        null=True,
        on_delete=models.SET_NULL
    )
    # Date when project was created
    date_created = models.DateTimeField(
        verbose_name='created',
        auto_now_add=True
    )
    # Project preview image (optional) - helps to recognize your project
    thumbnail = models.ImageField(
        verbose_name='thumbnail',
        upload_to=settings.PROJECT_THUMBNAILS_DIR,
        blank=True
    )
    # If project is not active, it was "deleted" by user
    is_active = models.BooleanField(
        verbose_name='activity',
        default=True
    )
    # Public projects are displayed for everybody
    # Private projects are displayed only for collaborators
    is_public = models.BooleanField(
        verbose_name='public',
        default=True
    )
    # Implements Many-To-Many relationship with UserProfile model
    users = models.ManyToManyField(
        User,
        related_name='projects'
    )

    def __str__(self):
        """
        Human-readable project representation.
        :return: string with project title and date when it was created.
        """
        return f'{self.title} ({self.date_created})'

    @property
    def thumbnail_url(self):
        """
        Gets path to the project thumbnail with specified name. if it
        does not exist, then replaces it with default thumbnail.
        :return: path to the project thumbnail.
        """
        if self.thumbnail and hasattr(self.thumbnail, 'url'):
            return self.thumbnail.url
        return os.path.join(settings.STATIC_URL, 'img', 'default', 'thumbnail.png')


class Category(models.Model):
    """
    User-defined category which card can be attached to.
    """
    # Category name
    name = models.CharField(
        verbose_name='name',
        max_length=64
    )
    # If category is not active, it was "deleted" by user
    is_active = models.BooleanField(
        verbose_name='activity',
        default=True
    )
    # Implements Many-To-Many relationship with Project model
    projects = models.ManyToManyField(
        Project,
        related_name='categories'
    )

    def __str__(self):
        """
        Human-readable category representation.
        :return: string with category name.
        """
        return self.name


class Card(models.Model):
    """
    Card represents a simple task or note, or anything that is important.
    """
    LOWEST = 0
    LOW = 1
    NORMAL = 2
    HIGH = 3
    VERY_HIGH = 4
    HIGHEST = 5

    PRIORITY_CHOICES = (
        (LOWEST, 'Lowest'),
        (LOW, 'Low'),
        (NORMAL, 'Normal'),
        (HIGH, 'High'),
        (VERY_HIGH, 'Very High'),
        (HIGHEST, 'Highest')
    )

    # A project where card is being stored
    project = models.ForeignKey(
        Project,
        verbose_name='project',
        on_delete=models.CASCADE
    )
    # Card name
    title = models.CharField(
        verbose_name='title',
        max_length=64
    )
    # Card text content
    description = models.TextField(
        verbose_name='content',
        max_length=512,
        blank=True
    )
    # Date when card was created
    date_created = models.DateTimeField(
        verbose_name='created',
        auto_now_add=True
    )
    # If card is not active, it was "deleted" by user
    is_active = models.BooleanField(
        verbose_name='activity',
        default=True
    )
    # Level of task importance
    priority = models.IntegerField(
        verbose_name='priority',
        choices=PRIORITY_CHOICES,
        default=NORMAL
    )
    # Task category (status)
    category = models.ForeignKey(
        Category,
        verbose_name='category',
        null=True,
        on_delete=models.SET_NULL,
        default=functools.partial(get_default_category_pk, name='TO-DO')
    )

    def __str__(self):
        """
        Human-readable card representation.
        :return: string with card title and date when it was created.
        """
        return f'{self.title} ({self.date_created})'

    @property
    def color(self):
        """
        Gets specific css class name depending on card priority level.
        :return: css class name.
        """
        return f'gp-project-card__lvl{self.priority}'

GeekPlanner/plannerapp/views.py
"""
Module for plannerapp views.
"""
from django.views.generic import DeleteView, CreateView, UpdateView, DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Project, Card, Category
from .forms import ProjectForm, CardForm, CategoryForm


def get_default_categories():
    """
    Gets list of predefined categories.
    :return: list of predefined Category objects.
    """
    return [
        Category.objects.get_or_create(name=name)[0]
        for name in ['TO-DO', 'Do Today', 'In Progress', 'Done']
    ]


@method_decorator(login_required, name='dispatch')
class ProjectListView(ListView):
    """Renders a list of projects available for the current user."""
    model = Project

    def get_queryset(self):
        """
        Get the list of items for this view.
        :return: list of active projects.
        """
        return super(ProjectListView, self).get_queryset().\
            filter(is_active=True).order_by('date_created')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(ProjectListView, self).get_context_data(**kwargs)
        context['title'] = 'Projects'
        return context


@method_decorator(login_required, name='dispatch')
class ProjectCreateView(CreateView):
    """Creates a new project."""
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy('planner:projects')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(ProjectCreateView, self).get_context_data(**kwargs)
        context['title'] = 'New project'
        return context

    def form_valid(self, form):
        """
        Validates form.
        :param form: form instance.
        :return: success_url by default.
        """
        form.instance.owner = self.request.user
        return super(ProjectCreateView, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class ProjectUpdateView(UpdateView):
    """Allows to edit information about project."""
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy('planner:projects')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(ProjectUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Edit project'
        return context


@method_decorator(login_required, name='dispatch')
class ProjectDeleteView(DeleteView):
    """Deletes selected project and returns to the updated list."""
    model = Project
    success_url = reverse_lazy('planner:projects')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(ProjectDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Delete project'
        return context


@method_decorator(login_required, name='dispatch')
class ProjectDetailView(DetailView):
    """Allows to work with project."""
    model = Project

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(ProjectDetailView, self).get_context_data(**kwargs)

        categories = self.get_project_categories(kwargs['object'].pk)
        categories_card_list = []
        for category in categories:
            cards = Card.objects.filter(
                Q(project=kwargs['object'].pk) &
                Q(is_active=True) &
                Q(category=category)
            )
            categories_card_list.append(cards)

        context['title'] = 'Project'
        context['categories'] = categories
        context['categories_card_list'] = categories_card_list
        return context

    def get_project_categories(self, project_pk):
        # TODO
        return [
            *get_default_categories(),
            # Category.objects.filter(projects=project_pk),
        ]


@method_decorator(login_required, name='dispatch')
class CardCreateView(CreateView):
    """Creates a new card."""
    model = Card
    form_class = CardForm

    def get_success_url(self):
        """
        Determines the URL to redirect to when the form is successfully validated.
        :return: success URL.
        """
        return reverse('planner:project_details', args=(self.kwargs['project_pk'],))

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add card'
        context['project_pk'] = self.kwargs['project_pk']
        return context

    def form_valid(self, form):
        """
        Validates form.
        :param form: form instance.
        :return: success_url by default.
        """
        form.instance.project = Project.objects.get(pk=self.kwargs['project_pk'])
        form.instance.category = Category.objects.get(pk=self.kwargs['category_pk'])
        return super(CardCreateView, self).form_valid(form)


@method_decorator(login_required, name='dispatch')
class CardUpdateView(UpdateView):
    """Allows to edit card data."""
    model = Card
    form_class = CardForm

    def get_success_url(self):
        """
        Determines the URL to redirect to when the form is successfully validated.
        :return: success URL.
        """
        return reverse('planner:project_details', args=(self.kwargs['project_pk'],))

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super().get_context_data(**kwargs)
        context['title'] = 'Edit card'
        context['project_pk'] = self.kwargs['project_pk']
        return context


@method_decorator(login_required, name='dispatch')
class CardDeleteView(DeleteView):
    """Deletes selected card and returns to the project."""
    model = Card

    def get_success_url(self):
        """
        Determines the URL to redirect to when the form is successfully validated.
        :return: success URL.
        """
        return reverse('planner:project_details', args=(self.kwargs['project_pk'],))

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(CardDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Delete card'
        context['project_pk'] = self.kwargs['project_pk']
        return context


@method_decorator(login_required, name='dispatch')
class CategoryCreateView(CreateView):
    """Creates new category (status block) in the project."""
    model = Category
    form_class = CategoryForm

    def get_success_url(self):
        """
        Determines the URL to redirect to when the form is successfully validated.
        :return: success URL.
        """
        return reverse('planner:project_details', args=(self.kwargs['project_pk'],))

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super().get_context_data(**kwargs)
        context['title'] = 'Add category'
        context['project_pk'] = self.kwargs['project_pk']
        return context


@method_decorator(login_required, name='dispatch')
class CategoryDeleteView(DeleteView):
    """Deletes category and returns to the project."""
    model = Card

    def get_success_url(self):
        """
        Determines the URL to redirect to when the form is successfully validated.
        :return: success URL.
        """
        return reverse('planner:project_details', args=(self.kwargs['project_pk'],))

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(CategoryDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Delete category'
        context['project_pk'] = self.kwargs['project_pk']
        return context

GeekPlanner/plannerapp/templates/plannerapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      GeekPlanner | {{ title }}
    {% endblock %}
  </title>
  {% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main/style.css' %}">
  {% endblock %}
</head>
<body>
  <div class="layout-wrapper">
    {% include 'mainapp/includes/inc_header.html' %}
    <main role="main">
      {% block content %}
      {% endblock %}
    </main>
  </div>
  {% include 'mainapp/includes/inc_footer.html' %}
</body>
</html>

GeekPlanner/plannerapp/templates/plannerapp/card_confirm_delete.html
{% extends 'plannerapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card my-4 gp-form">
        <form method="post">
          {% csrf_token %}
          <div class="card-header text-center text-uppercase font-weight-bold">
            Do you really want to delete this card?
          </div>
          <div class="d-flex justify-content-around px-4 py-4">
            <button class="btn btn-primary" type="submit">
              Delete
            </button>
            <a class="btn btn-primary" href="{% url 'planner:project_details' project_pk %}" type="button">
              Cancel
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/plannerapp/templates/plannerapp/card_form.html
{% extends 'plannerapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card my-4 gp-form">
        <div class="card-header text-center text-uppercase font-weight-bold">
          {{ title }}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data" id="card-create-form">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group">
                <label class="control-label small">
                  {{ field.name }}
                </label>
                {{ field }}
                <div class="gp-form__errors mt-2">
                  {% for error in field.errors %}
                    <div class="gp-form__error">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
            <div class="d-flex justify-content-around px-4 py-4">
              <input class="btn btn-primary" form="card-create-form" type="submit" value="Save">
              <a class="btn btn-primary" href="{% url 'planner:project_details' project_pk %}" type="button">
                Cancel
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/plannerapp/templates/plannerapp/category_confirm_delete.html
{% extends 'plannerapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card my-4 gp-form">
        <form method="post">
          {% csrf_token %}
          <div class="card-header text-center text-uppercase font-weight-bold">
            Do you really want to delete this category?
          </div>
          <div class="d-flex justify-content-around px-4 py-4">
            <button class="btn btn-primary" type="submit">
              Delete
            </button>
            <a class="btn btn-primary" href="{% url 'planner:projects' %}" type="button">
              Cancel
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/plannerapp/templates/plannerapp/category_form.html
{% extends 'plannerapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card my-4 gp-form">
        <div class="card-header text-center text-uppercase font-weight-bold">
          {{ title }}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data" id="project-create-form">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group">
                <label class="control-label small">
                  {{ field.name }}
                </label>
                {{ field }}
                <div class="gp-form__errors mt-2">
                  {% for error in field.errors %}
                    <div class="gp-form__error">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
            <div class="d-flex justify-content-around px-4 py-4">
              <input class="btn btn-primary" form="project-create-form" type="submit" value="Save">
              <a class="btn btn-primary" href="{% url 'planner:projects' %}" type="button">
                Cancel
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/plannerapp/templates/plannerapp/project_confirm_delete.html
{% extends 'plannerapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card my-4 gp-form">
        <form method="post">
          {% csrf_token %}
          <div class="card-header text-center text-uppercase font-weight-bold">
            Do you really want to delete this project?
          </div>
          <div class="d-flex justify-content-around px-4 py-4">
            <button class="btn btn-primary" type="submit">
              Delete
            </button>
            <a class="btn btn-primary" href="{% url 'planner:projects' %}" type="button">
              Cancel
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/plannerapp/templates/plannerapp/project_detail.html
{% extends 'plannerapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="gp-board my-2">
      <div class="gp-board__heading py-2">
        <div class="d-flex justify-content-between px-4">
          <div class="h3 font-weight-bold">
            {{ object.title }}
          </div>
          <div class="h5 font-weight-bold">
            {{ object.date_created }}
          </div>
        </div>
        <hr class="gp-board__hr">
        <div class="d-flex justify-content-between px-4">
          <div class="d-flex align-items-center py-2">
            <div class="h5">
              Team:
            </div>
            <div class="d-flex justify-content-start">
              <img class="gp-board__img" src="{{ object.owner.profile.avatar_url }}" alt="{{ object.owner.username }}">
              {% for user in object.users.all %}
                <img class="gp-board__img" src="{{ user.profile.avatar_url }}" alt="{{ user.username }}">
              {% endfor %}
            </div>
          </div>
        </div>
        <hr class="gp-board__hr">
      </div>
      <div class="gp-board__body px-2 py-2">
        <table class="table table-bordered">
          <thead>
            <tr>
              {% for category in categories %}
                <th scope="col">
                  <div class="d-flex justify-content-between align-items-center">
                    <div>
                      {{ category.name }}
                    </div>
                    <a class="btn btn-primary btn-sm gp-board__btn"
                       href="{% url 'planner:create_card' object.pk category.pk %}">
                      <i class="fa fa-plus" aria-hidden="true"></i>
                    </a>
                  </div>
                </th>
              {% endfor %}
            </tr>
          </thead>
          <tbody>
            <tr>
              {% for card_list in categories_card_list %}
                <td>
                  {% for card in card_list %}
                    <div class="card shadow-sm gp-project-card {{ card.color }}">
                      <div class="card-header">
                        <a class="btn btn-primary btn-sm gp-board__card-btn"
                           href="{% url 'planner:delete_card' card.pk object.pk %}">
                          <i class="fa fa-trash" aria-hidden="true"></i>
                        </a>
                        <div class="justify-content-between">
                          <h5>
                            {{ card.title }}
                          </h5>
                          <h5>
                            {{ card.date_created }}
                          </h5>
                        </div>
                      </div>
                      <div class="card-body">
                        {{ card.description }}
                      </div>
                      <a class="stretched-link" href="#"></a>
                    </div>
                  {% endfor %}
                </td>
              {% endfor %}
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/plannerapp/templates/plannerapp/project_list.html
{% extends 'plannerapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="container">
    <div class="gp-projects d-flex">
      <div class="py-4 gp-projects__left-sidebar">
        Меню
      </div>
      <div class="py-4 gp-projects__main flex-grow-1">
        <div class="px-3 gp-projects__main-menu">
          <h3>
            All projects
          </h3>
          <div class="d-flex justify-content-between align-items-center py-2">
            <span class="text-uppercase">
              {{ object_list|length }} project(s)
            </span>
            <div class="btn-group" role="group">
              <a class="btn btn-primary" href="{% url 'planner:create_project' %}">
                <i class="fa fa-plus" aria-hidden="true"></i>
              </a>
              <a class="btn btn-primary" href="#">
                <i class="fa fa-filter" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="px-3 py-2 gp-projects__main-content">
          {% for project in object_list %}
            <div class="my-2 d-flex align-content-stretch gp-projects__main-item rounded-top">
              <div class="gp-projects__main-thumbnail">
                <img class="gp-projects__main-img" src="{{ project.thumbnail_url }}" alt="ProjectThumbnail">
                <div class="gp-projects__main-owner text-align-center">
                  <div>
                    {{ project.date_created }}
                  </div>
                  <div>
                    {% if project.owner %}
                      {{ project.owner.first_name }}{{ project.owner.last_name }}
                    {% else %}
                      Unknown creator
                    {% endif %}
                  </div>
                </div>
              </div>
              <div class="gp-projects__main-summary">
                <div class="d-flex justify-content-between">
                  <a class="font-weight-bold" href="{% url 'planner:project_details' project.pk %}">
                    {{ project.title }}
                  </a>
                  <div class="btn-group" role="group">
                    <a class="btn btn-outline-primary" href="{% url 'planner:delete_project' project.pk %}">
                      <i class="fa fa-trash" aria-hidden="true"></i>
                    </a>
                    <a class="btn btn-outline-primary" href="{% url 'planner:update_project' project.pk %}">
                      <i class="fa fa-cogs" aria-hidden="true"></i>
                    </a>
                  </div>
                </div>
                <hr class="gp-hr">
                <div class="gp-projects__main-description">
                  {{ project.description }}
                </div>
                <hr class="gp-hr">
                <div class="container">
                  <div class="row">
                    <div class="col-8 gp-projects__main-tags">
                      <a class="btn tag" href="#">Python</a>
                      <a class="btn tag" href="#">VueJS</a>
                      <a class="btn tag" href="#">Django</a>
                      <a class="btn tag" href="#">Linux</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% empty %}
            <h5 class="text-uppercase text-center">
              No projects were found.
            </h5>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}