GeekPlanner/authapp/urls.py
"""
Module for authapp URLs.
"""
from django.urls import path, re_path
from django.views.generic.base import TemplateView

from django_registration.backends.activation.views import ActivationView, RegistrationView

from .views import LoginView, LogoutView, UserUpdateView,\
                    RegistrationClosedView, RegistrationCompleteView
from .forms import UserRegistrationForm


app_name = 'authapp'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'edit/',
        UserUpdateView.as_view(),
        name='edit'
    ),
    # Django-registration urls
    path(
        'register/',
        RegistrationView.as_view(
            form_class=UserRegistrationForm
        ),
        name='django_registration_register'
    ),
    path(
        'register/complete/',
        RegistrationCompleteView.as_view(),
        name='django_registration_complete'
    ),
    path(
        'register/closed/',
        RegistrationClosedView.as_view(),
        name='django_registration_closed'
    ),
    path(
        'activate/complete/',
        TemplateView.as_view(
            template_name='django_registration/activation_complete.html'
        ),
        name='django_registration_activation_complete'
    ),
    re_path(
        r'^activate/(?P<activation_key>[-:\w]+)/$',
        ActivationView.as_view(),
        name='django_registration_activate'
    ),
]

GeekPlanner/mainapp/urls.py
"""
Module for mainapp URLs.
"""
from django.urls import path

from .views import IndexView, PricingView


app_name = 'mainapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('pricing/', PricingView.as_view(), name='pricing'),
]

GeekPlanner/authapp/models.py
"""
Module for authapp models.
"""
import os

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.conf import settings

from django_registration.signals import user_activated


class User(AbstractUser):
    """Default user model."""


class UserProfile(models.Model):
    """UserProfile is an account which can be edited by user."""
    MALE = 'M'
    FEMALE = 'W'

    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )
    # Implements One-To-One relationship with User model
    user = models.OneToOneField(
        User,
        related_name='profile',
        on_delete=models.CASCADE
    )
    # User avatar
    avatar = models.ImageField(
        verbose_name='avatar',
        upload_to=settings.USER_AVATARS_DIR,
        blank=True
    )
    # User gender: male or female
    gender = models.CharField(
        verbose_name='gender',
        max_length=1,
        choices=GENDER_CHOICES,
        blank=True
    )

    @property
    def avatar_url(self):
        """
        Gets path to the user avatar with specified name. If it
        does not exist, then replaces it with default avatar.
        :return: path to the user avatar.
        """
        if self.avatar and hasattr(self.avatar, 'url'):
            return self.avatar.url
        return os.path.join(settings.STATIC_URL, 'img', 'default', 'avatar.png')


@receiver(user_activated)
def save_user_profile(sender, user, request, **kwargs):
    """
    Creates a profile associated with activated User instance.
    Triggered when user_activated signal is being emitted by the ActivationView.
    :param sender: ActivationView subclass used to activate the user.
    :param user: User instance representing the activated account.
    :param request: HttpRequest in which the account was activated.
    :param kwargs: additional key-value arguments.
    :return:
    """
    (user_profile, created) = UserProfile.objects.get_or_create(user=user)
    if created:
        user_profile.save()

GeekPlanner/authapp/forms.py
"""
Module for authapp forms.
"""
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm

from django_registration.forms import RegistrationForm

from authapp.models import User, UserProfile


class UserLoginForm(AuthenticationForm):
    """Form which appears when user clicks 'Login' button"""
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        """
        Applies Twitter Bootstrap styles to the form fields.
        :param args: additional arguments.
        :param kwargs: additional key-value arguments.
        """
        super(UserLoginForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class UserRegistrationForm(RegistrationForm):
    """Form for the two-step user authentication."""
    # Requires to fill the following additional fields of the form:
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.CharField(required=True)

    class Meta(RegistrationForm.Meta):
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email',)

    def __init__(self, *args, **kwargs):
        """
        Applies Twitter Bootstrap styles to the form fields.
        :param args: additional arguments.
        :param kwargs: additional key-value arguments.
        """
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class UserEditForm(UserChangeForm):
    """Form which appears when user clicks 'Edit' button"""
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password',)

    def __init__(self, *args, **kwargs):
        """
        Applies Twitter Bootstrap styles to the form fields.
        :param args: additional arguments.
        :param kwargs: additional key-value arguments.
        """
        super(UserEditForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class UserProfileEditForm(forms.ModelForm):
    """Form which contains additional information of User to edit."""
    class Meta:
        model = UserProfile
        fields = ('avatar', 'gender',)

    def __init__(self, *args, **kwargs):
        """
        Applies Twitter Bootstrap styles to the form fields.
        :param args: additional arguments.
        :param kwargs: additional key-value arguments.
        """
        super(UserProfileEditForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

GeekPlanner/authapp/views.py
"""
Module for authapp views.
"""
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import FormView, RedirectView, TemplateView
from django.views.decorators.debug import sensitive_post_parameters
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.urls import reverse, reverse_lazy
from django.utils.http import is_safe_url
from django.utils.decorators import method_decorator
from django.db import transaction

from .forms import UserLoginForm, UserEditForm, UserProfileEditForm


class LoginView(FormView):
    """Logs user in."""
    form_class = UserLoginForm
    template_name = 'authapp/login.html'

    def get_success_url(self):
        """
        Determines the URL to redirect to when the form is successfully validated.
        :return: success URL.
        """
        next_url = self.request.GET.get('next')
        if is_safe_url(url=next_url, host=self.request.get_host()):
            return next_url
        return reverse('main:index')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super().get_context_data(**kwargs)
        context['title'] = 'Вход'
        return context

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        """
        The view part of the view – the method that accepts a request argument
        plus arguments, and returns a HTTP response.
        :param request: request object.
        :param args: additional arguments.
        :param kwargs: additional key-value arguments.
        :return: HTTP response.
        """
        request.session.set_test_cookie()
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        """
        Validates form.
        :param form: form instance.
        :return: success_url by default.
        """
        login(self.request, form.get_user())
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()
        return super(LoginView, self).form_valid(form)


class LogoutView(RedirectView):
    """Logs user out"""
    url = reverse_lazy('main:index')

    def get(self, request, *args, **kwargs):
        """
        Handles GET request.
        :param request: request object.
        :param args: additional arguments.
        :param kwargs: additional key-value arguments.
        :return: HTTP response.
        """
        if self.request.user.is_authenticated:
            logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class RegistrationCompleteView(TemplateView):
    """View for a page which congratulates user with successful registration."""
    template_name = 'django_registration/registration_complete.html'

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(RegistrationCompleteView, self).get_context_data(**kwargs)
        context['title'] = 'Регистрация завершена'
        return context


class RegistrationClosedView(TemplateView):
    """
    View for a page which shows instead of registration form in case of the flag:
    settings.REGISTRATION_OPEN = False
    """
    template_name = 'django_registration/registration_closed.html'

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(RegistrationClosedView, self).get_context_data(**kwargs)
        context['title'] = 'Регистрация закрыта'
        return context


@method_decorator(login_required, name='dispatch')
class UserUpdateView(FormView):
    """Allows to edit User form."""
    template_name = 'authapp/user_update_form.html'
    success_url = reverse_lazy('main:index')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        return {'title': 'Редактирование профиля'}

    def get(self, request, *args, **kwargs):
        """
        Handles GET request.
        :param request: request object.
        :param args: additional arguments.
        :param kwargs: additional key-value arguments.
        :return: HTTP response.
        """
        context = self.get_context_data()
        context['user_form'] = UserEditForm(instance=request.user)
        context['profile_form'] = UserProfileEditForm(instance=request.user.profile)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """
        Handles POST request.
        :param request: request object.
        :param args: additional arguments.
        :param kwargs: additional key-value arguments.
        :return: HTTP response.
        """
        user_form = UserEditForm(
            self.request.POST, self.request.FILES, instance=request.user
        )
        profile_form = UserProfileEditForm(
            self.request.POST, instance=request.user.profile
        )

        if user_form.is_valid() and profile_form.is_valid():
            with transaction.atomic():
                user_form.save()
                profile_form.save()
            return HttpResponseRedirect(reverse('main:index'))

        context = self.get_context_data()
        context['user_form'] = user_form
        context['profile_form'] = profile_form

        return render(request, self.template_name, context)

GeekPlanner/authapp/templates/django_registration/activation_complete.html
{% extends 'authapp/base.html' %}

{% block content %}
  <div class="container justify-content-center">
    <div class="my-4 jumbotron">
      <h1 class="text-uppercase">
        Activation success
      </h1>
      <p class="lead">
        Now you can create your first project by going to the "Projects" section.
      </p>
      <hr class="my-4">
      <p class="lead">
        <a class="btn btn-primary" href="{% url 'mainapp:index' %}">
          OK
        </a>
      </p>
    </div>
  </div>
{% endblock %}

GeekPlanner/authapp/templates/django_registration/activation_failed.html
{% extends 'authapp/base.html' %}

{% block content %}
  <div class="container justify-content-center">
    <div class="my-4 jumbotron">
      <h1 class="text-uppercase">
        Activation error
      </h1>
      <p class="lead">
        {{ activation_error }}
      </p>
      <p class="lead">
        Follow the instruction in the message we sent to your Email!
      </p>
      <hr class="my-4">
      <p class="lead">
        <a class="btn btn-primary" href="{% url 'mainapp:index' %}">
          OK
        </a>
      </p>
    </div>
  </div>
{% endblock %}

GeekPlanner/authapp/templates/django_registration/registration_closed.html
{% extends 'authapp/base.html' %}

{% block content %}
  <div class="container justify-content-center">
    <div class="my-4 jumbotron">
      <h1 class="text-uppercase">
        Registration is currently unavailable.
      </h1>
      <p class="lead">
        Sorry for inconvenience, but GeekPlanner does not accept new users at the moment.
      </p>
      <hr class="my-4">
      <p class="lead">
        <a class="btn btn-primary" href="{% url 'mainapp:index' %}">
          OK
        </a>
      </p>
    </div>
  </div>
{% endblock %}

GeekPlanner/authapp/templates/django_registration/registration_complete.html
{% extends 'authapp/base.html' %}

{% block content %}
  <div class="container justify-content-center">
    <div class="my-4 jumbotron">
      <h1 class="text-uppercase">
        Activation key has been sent
      </h1>
      <p class="lead">
        Check you email and follow sent instructions. Note that sometimes email can be in the spam directory.
      </p>
      <hr class="my-4">
      <p class="lead">
        <a class="btn btn-primary" href="{% url 'mainapp:index' %}">
          OK
        </a>
      </p>
    </div>
  </div>
{% endblock %}

GeekPlanner/authapp/templates/django_registration/registration_form.html
{% extends 'authapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card my-4 gp-form">
        <div class="card-header text-center text-uppercase font-weight-bold">
          Registration
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data" id="register-form">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group">
                <label class="control-label small">
                  {{ field.label }}
                </label>
                {{ field }}
                <div class="gp-form__errors mt-2">
                  {% for error in field.errors %}
                    <div class="gp-form__error">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
            <input class="btn btn-primary col-12" form="register-form" type="submit" value="Register">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}