GeekPlanner/adminapp/urls.py
"""
Module for adminapp URLs.
"""
from django.urls import path

import adminapp.views as adminapp


app_name = 'adminapp'

urlpatterns = [
    # ========================================================================
    # User URLs
    # ========================================================================
    path(
        'users/',
        adminapp.UserListView.as_view(),
        name='users'
    ),
    path(
        'create_user/',
        adminapp.UserCreateView.as_view(),
        name='create_user'
    ),
    path(
        'read_user/<int:pk>/',
        adminapp.UserReadView.as_view(),
        name='read_user'
    ),
    path(
        'update_user/<int:pk>/',
        adminapp.UserUpdateView.as_view(),
        name='update_user'
    ),
    path(
        'delete_user/<int:pk>/',
        adminapp.UserDeleteView.as_view(),
        name='delete_user'
    ),
    # ========================================================================
    # Project URLs
    # ========================================================================
    path(
        'projects/',
        adminapp.ProjectListView.as_view(),
        name='projects'
    ),
    path(
        'create_project/',
        adminapp.ProjectCreateView.as_view(),
        name='create_project'
    ),
    # path(
    #     'read_project/',
    #     adminapp.ProjectDetailView.as_view(),
    #     name='read_project'
    # ),
    path(
        'update_project/<int:pk>/',
        adminapp.ProjectUpdateView.as_view(),
        name='update_project'
    ),
    path(
        'delete_project/<int:pk>/',
        adminapp.ProjectDeleteView.as_view(),
        name='delete_project'
    ),
    # ========================================================================
    # Category URLs
    # ========================================================================
    path(
        'categories/',
        adminapp.CategoryListView.as_view(),
        name='categories'
    ),
    path(
        'create_category/',
        adminapp.CategoryCreateView.as_view(),
        name='create_category'
    ),
    # path(
    #     'update_category/',
    #     adminapp.CategoryEditView.as_view(),
    #     name='update_category'
    # ),
    # path(
    #     'delete_category/',
    #     adminapp.CategoryDeleteView.as_view(),
    #     name='delete_category'
    # )
]

GeekPlanner/authapp/urls.py
"""
Module for authapp URLs.
"""
from django.urls import path, re_path
from django.views.generic.base import TemplateView

from django_registration.backends.activation.views import ActivationView, RegistrationView

from .views import LoginView, LogoutView, UserUpdateView,\
                    RegistrationClosedView, RegistrationCompleteView
from .forms import UserRegistrationForm


app_name = 'authapp'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'edit/',
        UserUpdateView.as_view(),
        name='edit'
    ),
    # Django-registration urls
    path(
        'register/',
        RegistrationView.as_view(
            form_class=UserRegistrationForm
        ),
        name='django_registration_register'
    ),
    path(
        'register/complete/',
        RegistrationCompleteView.as_view(),
        name='django_registration_complete'
    ),
    path(
        'register/closed/',
        RegistrationClosedView.as_view(),
        name='django_registration_closed'
    ),
    path(
        'activate/complete/',
        TemplateView.as_view(
            template_name='django_registration/activation_complete.html'
        ),
        name='django_registration_activation_complete'
    ),
    re_path(
        r'^activate/(?P<activation_key>[-:\w]+)/$',
        ActivationView.as_view(),
        name='django_registration_activate'
    ),
]

GeekPlanner/plannerapp/urls.py
"""
Module for plannerapp URLs.
"""
from django.urls import path

import plannerapp.views as plannerapp


app_name = 'plannerapp'

urlpatterns = [
    path(
        'projects/',
        plannerapp.ProjectListView.as_view(),
        name='projects'
    ),
    path(
        'create_project/',
        plannerapp.ProjectCreateView.as_view(),
        name='create_project'
    ),
    path(
        'update_project/<int:pk>/',
        plannerapp.ProjectUpdateView.as_view(),
        name='update_project'
    ),
    path(
        'delete_project/<int:pk>/',
        plannerapp.ProjectDeleteView.as_view(),
        name='delete_project'
    ),
    path(
        'project_details/<int:pk>/',
        plannerapp.ProjectDetailView.as_view(),
        name='project_details'
    ),
    path(
        'create_card/project/<int:project_pk>/category/<int:category_pk>/',
        plannerapp.CardCreateView.as_view(),
        name='create_card'
    ),
    path(
        'delete_card/<int:pk>/project/<int:project_pk>/',
        plannerapp.CardDeleteView.as_view(),
        name='delete_card'
    ),
    path(
        'update_card/<int:pk>/project/<int:project_pk>/',
        plannerapp.CardUpdateView.as_view(),
        name='update_card'
    ),
    path(
        'create_category/<int:pk>/project/<int:project_pk>/',
        plannerapp.CategoryCreateView.as_view(),
        name='create_category',
    ),
    # path(
    #     'update_category/<int:pk>/project/<int:project_pk>/',
    #     plannerapp.CategoryUpdateView.as_view(),
    #     name='update_category',
    # ),
    path(
        'delete_category/<int:pk>/project/<int:project_pk>/',
        plannerapp.CategoryDeleteView.as_view(),
        name='delete_category',
    )
]

GeekPlanner/adminapp/forms.py
"""
Module for adminapp forms.
"""
from django.contrib.auth.forms import UserCreationForm

from authapp.models import User


class UserCreateForm(UserCreationForm):
    """Form which allows admin to create a new user account."""
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email',)

    def __init__(self, *args, **kwargs):
        """
        Applies Twitter Bootstrap styles to the form fields.
        :param args: additional arguments.
        :param kwargs: additional key-value arguments.
        """
        super(UserCreateForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

GeekPlanner/adminapp/views.py
"""
Module for adminapp views.
"""
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, DeleteView, UpdateView, FormView, DetailView
from django.views.generic.list import ListView
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test
from django.db import transaction

from adminapp.forms import UserCreateForm
from authapp.models import User
from authapp.forms import UserEditForm, UserProfileEditForm
from plannerapp.models import Project, Category
from plannerapp.forms import ProjectForm, CategoryForm


@method_decorator(user_passes_test(lambda user: user.is_superuser), name='dispatch')
class UserListView(ListView):
    """Renders list of all users."""
    template_name = 'adminapp/user_list.html'
    model = User

    def get_queryset(self):
        """
        Get the list of items for this view.
        :return: list of active projects.
        """
        return super(UserListView, self).get_queryset()\
            .filter(is_superuser=False).order_by('id')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(UserListView, self).get_context_data(**kwargs)
        context['title'] = 'Users'
        context['create_url'] = reverse('admin:create_user')
        return context


@method_decorator(user_passes_test(lambda user: user.is_superuser), name='dispatch')
class UserCreateView(CreateView):
    """
    Creates user without a need of authentication via activation link.
    This functionality is allowed ONLY for administrators and superusers who have
    an access to the admin board.
    """
    template_name = 'adminapp/user_form.html'
    form_class = UserCreateForm
    success_url = reverse_lazy('admin:users')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(UserCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Create user'
        return context


@method_decorator(user_passes_test(lambda user: user.is_superuser), name='dispatch')
class UserReadView(DetailView):
    template_name = 'adminapp/user_detail.html'
    model = User

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(UserReadView, self).get_context_data(**kwargs)
        context['title'] = 'User information'
        return context


@method_decorator(user_passes_test(lambda user: user.is_superuser), name='dispatch')
class UserUpdateView(FormView):
    """Allows to edit User form."""
    template_name = 'adminapp/user_update_form.html'
    success_url = reverse_lazy('admin:users')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        return {'title': 'Update user'}

    def get(self, request, *args, **kwargs):
        """
        Handles GET request.
        :param request: request object.
        :param args: additional arguments.
        :param kwargs: additional key-value arguments.
        :return: HTTP response.
        """
        context = self.get_context_data()
        user = User.objects.get(pk=kwargs['pk'])
        context['user_form'] = UserEditForm(instance=user)
        context['profile_form'] = UserProfileEditForm(instance=user.profile)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        """
        Handles POST request.
        :param request: request object.
        :param args: additional arguments.
        :param kwargs: additional key-value arguments.
        :return: HTTP response.
        """
        user = User.objects.get(pk=kwargs['pk'])

        user_form = UserEditForm(
            self.request.POST,
            self.request.FILES,
            instance=user
        )
        profile_form = UserProfileEditForm(
            self.request.POST,
            instance=user.profile,
        )

        if user_form.is_valid() and profile_form.is_valid():
            with transaction.atomic():
                user_form.save()
                profile_form.save()
            return HttpResponseRedirect(reverse('admin:users'))

        context = self.get_context_data()
        context['user_form'] = user_form
        context['profile_form'] = profile_form

        return render(request, self.template_name, context)


@method_decorator(user_passes_test(lambda user: user.is_superuser), name='dispatch')
class UserDeleteView(DeleteView):
    """Deletes selected user and returns to the updated list."""
    template_name = 'adminapp/user_confirm_delete.html'
    model = User
    success_url = reverse_lazy('admin:users')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(UserDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Delete user'
        return context


@method_decorator(user_passes_test(lambda user: user.is_superuser), name='dispatch')
class ProjectListView(ListView):
    """Renders list of all projects."""
    template_name = 'adminapp/project_list.html'
    model = Project

    def get_queryset(self):
        """
        Get the list of items for this view.
        :return: list of active projects.
        """
        return super(ProjectListView, self).get_queryset().order_by('id')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(ProjectListView, self).get_context_data(**kwargs)
        context['title'] = 'Projects'
        context['create_url'] = reverse('admin:create_project')
        return context


@method_decorator(user_passes_test(lambda user: user.is_superuser), name='dispatch')
class ProjectCreateView(CreateView):
    """Creates a new project."""
    template_name = 'adminapp/project_form.html'
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy('admin:projects')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(ProjectCreateView, self).get_context_data(**kwargs)
        context['title'] = 'New project'
        return context

    def form_valid(self, form):
        """
        Validates form.
        :param form: form instance.
        :return: success_url by default.
        """
        form.instance.owner = self.request.user
        return super(ProjectCreateView, self).form_valid(form)


@method_decorator(user_passes_test(lambda user: user.is_superuser), name='dispatch')
class ProjectUpdateView(UpdateView):
    """Allows to edit information about project."""
    template_name = 'adminapp/project_update_form.html'
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy('admin:projects')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(ProjectUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Edit project'
        return context


@method_decorator(user_passes_test(lambda user: user.is_superuser), name='dispatch')
class ProjectDeleteView(DeleteView):
    """Deletes selected project and returns to the updated list."""
    template_name = 'adminapp/project_confirm_delete.html'
    model = Project
    success_url = reverse_lazy('admin:projects')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(ProjectDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Delete project'
        return context


@method_decorator(user_passes_test(lambda user: user.is_superuser), name='dispatch')
class CategoryListView(ListView):
    """Renders list of all categories."""
    template_name = 'adminapp/category_list.html'
    model = Category

    def get_queryset(self):
        """
        Get the list of items for this view.
        :return: list of active projects.
        """
        return super(CategoryListView, self).get_queryset().order_by('name')

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['title'] = 'Categories'
        context['create_url'] = reverse('admin:create_category')
        return context


@method_decorator(user_passes_test(lambda user: user.is_superuser), name='dispatch')
class CategoryCreateView(CreateView):
    form_class = CategoryForm

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.

GeekPlanner/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      GeekPlanner
    {% endblock %}
  </title>
  {% block css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/admin/style.css' %}">
  {% endblock %}
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      {% include 'adminapp/includes/inc_sidebar.html' %}
      <main role="main" class="gp-admin-body col">
        {% include 'adminapp/includes/inc_search_panel.html' %}
        {% block content %}
        {% endblock %}
      </main>
    </div>
  </div>
</body>
</html>

GeekPlanner/adminapp/templates/adminapp/category_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card my-4 gp-form">
        <div class="card-header text-center text-uppercase font-weight-bold">
          Create category
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data" id="create-form">
            {% csrf_token %}
            {% for field in register_form %}
              <div class="form-group">
                <label class="control-label small">
                  {{ field.label }}
                </label>
                {{ field }}
                <div class="gp-form__errors mt-2">
                  {% for error in field.errors %}
                    <div class="gp-form__error">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
            <input class="btn btn-primary col-12" form="create-form" type="submit" value="Create">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/adminapp/templates/adminapp/category_list.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row py-4">
      <div class="col">
        {% for category in object_list %}
          <div class="card mb-2">
            <div class="card-body">
              {{ category.name }}
            </div>
            <div class="card-footer d-flex justify-content-around">
              {% if user.is_active %}
                <a href="{% url 'admin:delete_category' category.pk %}" class="btn btn-primary btn-fa">
                  <i class="fa fa-trash" aria-hidden="true"></i>
                </a>
                <a href="{% url 'admin:update_category' category.pk %}" class="btn btn-primary btn-fa">
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                </a>
              {% else %}
                <a href="#" class="btn btn-primary btn-fa">
                  <i class="fa fa-undo" aria-hidden="true"></i>
                </a>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/adminapp/templates/adminapp/project_confirm_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card my-4 gp-form">
        <form method="post">
          {% csrf_token %}
          <div class="card-header text-center text-uppercase font-weight-bold">
            Do you really want to delete this project?
          </div>
          <div class="d-flex justify-content-around px-4 py-4">
            <button class="btn btn-primary" type="submit">
              Delete
            </button>
            <a class="btn btn-primary" href="{% url 'admin:projects' %}" type="button">
              Cancel
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/adminapp/templates/adminapp/project_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card my-4 gp-form">
        <div class="card-header text-center text-uppercase font-weight-bold">
          {{ title }}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data" id="project-create-form">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group">
                <label class="control-label small">
                  {{ field.name }}
                </label>
                {{ field }}
                <div class="gp-form__errors mt-2">
                  {% for error in field.errors %}
                    <div class="gp-form__error">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
            <div class="d-flex justify-content-around px-4 py-4">
              <input class="btn btn-primary" form="project-create-form" type="submit" value="Save">
              <a class="btn btn-primary" href="{% url 'admin:projects' %}">
                Cancel
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/adminapp/templates/adminapp/project_list.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="d-flex py-4">
      {% for project in object_list %}
        <div class="card border-dark mb-3 gp-card">
          <div class="card-header d-flex justify-content-center">
            <h6>
              {{ project.title }}
            </h6>
          </div>
          <div class="card-body d-flex justify-content-center">
            <img class="gp-card__img" src="{{ project.thumbnail_url }}" alt="{{ project.title }}">
          </div>
          <div class="card-footer d-flex justify-content-around">
            {% if user.is_active %}
              <a href="{% url 'admin:delete_project' project.pk %}" class="btn btn-primary btn-fa">
                <i class="fa fa-trash" aria-hidden="true"></i>
              </a>
              <a href="{% url 'admin:update_project' project.pk %}" class="btn btn-primary btn-fa">
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              </a>
              <a href="#" class="btn btn-primary btn-fa">
                <i class="fa fa-info-circle" aria-hidden="true"></i>
              </a>
            {% else %}
              <a href="#" class="btn btn-primary btn-fa">
                <i class="fa fa-undo" aria-hidden="true"></i>
              </a>
            {% endif %}
          </div>
        </div>
      {% empty %}
        <h5 class="text-uppercase text-center">
          No projects were found.
        </h5>
      {% endfor %}
    </div>
  </div>
{% endblock %}

GeekPlanner/adminapp/templates/adminapp/project_update_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card my-4 gp-form">
        <div class="card-header text-center text-uppercase font-weight-bold">
          {{ title }}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data" id="project-create-form">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group">
                <label class="control-label small">
                  {{ field.name }}
                </label>
                {{ field }}
                <div class="gp-form__errors mt-2">
                  {% for error in field.errors %}
                    <div class="gp-form__error">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
            <div class="d-flex justify-content-around px-4 py-4">
              <input class="btn btn-primary" form="project-create-form" type="submit" value="Сохранить">
              <a class="btn btn-primary" href="{% url 'admin:projects' %}" type="button">
                Cancel
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/adminapp/templates/adminapp/user_confirm_delete.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card my-4 gp-form">
        <form method="post">
          {% csrf_token %}
          <div class="card-header text-center text-uppercase font-weight-bold">
            Do you really want to delete this user?
          </div>
          <div class="d-flex justify-content-around px-4 py-4">
            <button class="btn btn-primary" type="submit">
              Delete
            </button>
            <a class="btn btn-primary" href="{% url 'admin:users' %}" type="button">
              Cancel
            </a>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/adminapp/templates/adminapp/user_detail.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="d-flex py-4">
      <div class="card border-dark mb-3 gp-card">
        <div class="card-header d-flex justify-content-around">
          <h6>
            {{ user.first_name }} <i>@{{ user.username }}</i> {{ user.last_name }}
          </h6>
        </div>
        <div class="card-body d-flex align-items-center flex-lg-column">
          <img class="gp-card__img" src="{{ user.profile.avatar_url }}" alt="{{ user.username }}">
          <ul>
            <li>Email: {{ user.email }}</li>
            <li>Age: {{ user.profile.age }}</li>
          </ul>
        </div>
        <div class="card-footer d-flex justify-content-around">
          <a href="{% url 'admin:users' %}" class="btn btn-primary">
            Back
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/adminapp/templates/adminapp/user_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card my-4 gp-form">
        <div class="card-header text-center text-uppercase font-weight-bold">
          {{ title }}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data" id="create-form">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group">
                <label class="control-label small">
                  {{ field.label }}
                </label>
                {{ field }}
                <div class="gp-form__errors mt-2">
                  {% for error in field.errors %}
                    <div class="gp-form__error">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
            <input class="btn btn-primary col-12" form="create-form" type="submit" value="Create">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

GeekPlanner/adminapp/templates/adminapp/user_list.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="d-flex py-4">
      {% for user in object_list %}
        <div class="card border-dark mb-3 gp-card">
          <div class="card-header d-flex justify-content-around">
            <h6>
              {{ user.first_name }} <i>@{{ user.username }}</i> {{ user.last_name }}
            </h6>
          </div>
          <div class="card-body d-flex justify-content-center">
            <img class="gp-card__img" src="{{ user.profile.avatar_url }}" alt="{{ user.username }}">
          </div>
          <div class="card-footer d-flex justify-content-around">
            {% if user.is_active %}
              <a href="{% url 'admin:delete_user' user.pk %}" class="btn btn-primary btn-fa">
                <i class="fa fa-trash" aria-hidden="true"></i>
              </a>
              <a href="{% url 'admin:update_user' user.pk %}" class="btn btn-primary btn-fa">
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              </a>
              <a href="{% url 'admin:read_user' user.pk %}" class="btn btn-primary btn-fa">
                <i class="fa fa-info-circle" aria-hidden="true"></i>
              </a>
            {% else %}
              <a href="#" class="btn btn-primary btn-fa">
                <i class="fa fa-undo" aria-hidden="true"></i>
              </a>
            {% endif %}
          </div>
        </div>
      {% empty %}
        <h5 class="text-uppercase text-center">
          No users were found.
        </h5>
      {% endfor %}
    </div>
  </div>
{% endblock %}

GeekPlanner/adminapp/templates/adminapp/user_update_form.html
{% extends 'adminapp/base.html' %}

{% block content %}
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="card my-4 gp-form">
        <div class="card-header text-center text-uppercase font-weight-bold">
          {{ title }}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data" id="user-update-form">
            {% csrf_token %}
            {% for field in user_form %}
              <div class="form-group">
                <label class="control-label small">
                  {{ field.name }}
                </label>
                {{ field }}
                <div class="gp-form__errors mt-2">
                  {% for error in field.errors %}
                    <div class="gp-form__error">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
            {% for field in profile_form %}
              <div class="form-group">
                <label class="control-label small">
                  {{ field.name }}
                </label>
                {{ field }}
                <div class="gp-form__errors mt-2">
                  {% for error in field.errors %}
                    <div class="gp-form__error">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                </div>
              </div>
            {% endfor %}
            <div class="d-flex justify-content-around px-4 py-4">
              <input class="btn btn-primary" form="user-update-form" type="submit" value="Save">
              <a class="btn btn-primary" href="{% url 'admin:users' %}">
                Cancel
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}