GeekPlanner/adminapp/urls.py
"""
Module for adminapp URLs.
"""
from django.urls import path

import adminapp.views as adminapp


app_name = 'adminapp'

urlpatterns = [
    # ========================================================================
    # User URLs
    # ========================================================================
    path(
        'users/',
        adminapp.UserListView.as_view(),
        name='users'
    ),
    path(
        'create_user/',
        adminapp.UserCreateView.as_view(),
        name='create_user'
    ),
    path(
        'read_user/<int:pk>/',
        adminapp.UserReadView.as_view(),
        name='read_user'
    ),
    path(
        'update_user/<int:pk>/',
        adminapp.UserUpdateView.as_view(),
        name='update_user'
    ),
    path(
        'delete_user/<int:pk>/',
        adminapp.UserDeleteView.as_view(),
        name='delete_user'
    ),
    # ========================================================================
    # Project URLs
    # ========================================================================
    path(
        'projects/',
        adminapp.ProjectListView.as_view(),
        name='projects'
    ),
    path(
        'create_project/',
        adminapp.ProjectCreateView.as_view(),
        name='create_project'
    ),
    # path(
    #     'read_project/',
    #     adminapp.ProjectDetailView.as_view(),
    #     name='read_project'
    # ),
    path(
        'update_project/<int:pk>/',
        adminapp.ProjectUpdateView.as_view(),
        name='update_project'
    ),
    path(
        'delete_project/<int:pk>/',
        adminapp.ProjectDeleteView.as_view(),
        name='delete_project'
    ),
    # ========================================================================
    # Category URLs
    # ========================================================================
    path(
        'categories/',
        adminapp.CategoryListView.as_view(),
        name='categories'
    ),
    path(
        'create_category/',
        adminapp.CategoryCreateView.as_view(),
        name='create_category'
    ),
    # path(
    #     'update_category/',
    #     adminapp.CategoryEditView.as_view(),
    #     name='update_category'
    # ),
    # path(
    #     'delete_category/',
    #     adminapp.CategoryDeleteView.as_view(),
    #     name='delete_category'
    # )
]

GeekPlanner/authapp/urls.py
"""
Module for authapp URLs.
"""
from django.urls import path, re_path
from django.views.generic.base import TemplateView

from django_registration.backends.activation.views import ActivationView, RegistrationView

from .views import LoginView, LogoutView, UserUpdateView,\
                    RegistrationClosedView, RegistrationCompleteView
from .forms import UserRegistrationForm


app_name = 'authapp'

urlpatterns = [
    path(
        'login/',
        LoginView.as_view(),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='logout'
    ),
    path(
        'edit/',
        UserUpdateView.as_view(),
        name='edit'
    ),
    # Django-registration urls
    path(
        'register/',
        RegistrationView.as_view(
            form_class=UserRegistrationForm
        ),
        name='django_registration_register'
    ),
    path(
        'register/complete/',
        RegistrationCompleteView.as_view(),
        name='django_registration_complete'
    ),
    path(
        'register/closed/',
        RegistrationClosedView.as_view(),
        name='django_registration_closed'
    ),
    path(
        'activate/complete/',
        TemplateView.as_view(
            template_name='django_registration/activation_complete.html'
        ),
        name='django_registration_activation_complete'
    ),
    re_path(
        r'^activate/(?P<activation_key>[-:\w]+)/$',
        ActivationView.as_view(),
        name='django_registration_activate'
    ),
]

GeekPlanner/mainapp/urls.py
"""
Module for mainapp URLs.
"""
from django.urls import path

from .views import IndexView, PricingView


app_name = 'mainapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('pricing/', PricingView.as_view(), name='pricing'),
]

GeekPlanner/plannerapp/urls.py
"""
Module for plannerapp URLs.
"""
from django.urls import path

import plannerapp.views as plannerapp


app_name = 'plannerapp'

urlpatterns = [
    path(
        'projects/',
        plannerapp.ProjectListView.as_view(),
        name='projects'
    ),
    path(
        'create_project/',
        plannerapp.ProjectCreateView.as_view(),
        name='create_project'
    ),
    path(
        'update_project/<int:pk>/',
        plannerapp.ProjectUpdateView.as_view(),
        name='update_project'
    ),
    path(
        'delete_project/<int:pk>/',
        plannerapp.ProjectDeleteView.as_view(),
        name='delete_project'
    ),
    path(
        'project_details/<int:pk>/',
        plannerapp.ProjectDetailView.as_view(),
        name='project_details'
    ),
    path(
        'create_card/project/<int:project_pk>/category/<int:category_pk>/',
        plannerapp.CardCreateView.as_view(),
        name='create_card'
    ),
    path(
        'delete_card/<int:pk>/project/<int:project_pk>/',
        plannerapp.CardDeleteView.as_view(),
        name='delete_card'
    ),
    path(
        'update_card/<int:pk>/project/<int:project_pk>/',
        plannerapp.CardUpdateView.as_view(),
        name='update_card'
    ),
    path(
        'create_category/<int:pk>/project/<int:project_pk>/',
        plannerapp.CategoryCreateView.as_view(),
        name='create_category',
    ),
    # path(
    #     'update_category/<int:pk>/project/<int:project_pk>/',
    #     plannerapp.CategoryUpdateView.as_view(),
    #     name='update_category',
    # ),
    path(
        'delete_category/<int:pk>/project/<int:project_pk>/',
        plannerapp.CategoryDeleteView.as_view(),
        name='delete_category',
    )
]

GeekPlanner/mainapp/views.py
"""
Module for mainapp views.
"""
from django.views.generic.base import TemplateView


class IndexView(TemplateView):
    """Index page view."""
    template_name = 'mainapp/index.html'

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(IndexView, self).get_context_data(**kwargs)
        context['title'] = 'Main'
        return context


class PricingView(TemplateView):
    """Pricing page view."""
    template_name = 'mainapp/pricing.html'

    def get_context_data(self, **kwargs):
        """
        Returns context data for displaying the object.
        :param kwargs: additional key-value arguments.
        :return: context data for the template.
        """
        context = super(PricingView, self).get_context_data(**kwargs)
        context['title'] = 'Pricing'
        return context

GeekPlanner/mainapp/templates/mainapp/includes/inc_footer.html
<footer class="footer font-small mt-auto">
  <div class="container text-center text-md-left">
    <div class="row">
      <div class="col-md-3 mx-auto">
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">
          Learn more
        </h5>
        <ul class="list-unstyled">
          <li>
            <a href="#">
              Tour
            </a>
          </li>
          <li>
            <a href="#">
              Project demo
            </a>
          </li>
          <li>
            <a href="#">
              New features
            </a>
          </li>
        </ul>
      </div>
      <hr class="clearfix w-100 d-md-none">
      <div class="col-md-3 mx-auto">
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">
          Support
        </h5>
        <ul class="list-unstyled">
          <li>
            <a href="#">
              Terms
            </a>
          </li>
          <li>
            <a href="#">
              Privacy & Security
            </a>
          </li>
          <li>
            <a href="#">
              Status
            </a>
          </li>
          <li>
            <a href="#">
              Help
            </a>
          </li>
        </ul>
      </div>
      <hr class="clearfix w-100 d-md-none">
      <div class="col-md-3 mx-auto">
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">
          About
        </h5>
        <ul class="list-unstyled">
          <li>
            <a href="#">
              About GeekPlanner
            </a>
          </li>
          <li>
            <a href="#">
              GitHub
            </a>
          </li>
          <li>
            <a href="#">
              Twitter
            </a>
          </li>
          <li>
            <a href="#">
              Blog
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright text-center py-3">
    © 2019 Copyright:<a href="#"> geekplanner.com</a>
  </div>
</footer>

GeekPlanner/mainapp/templates/mainapp/includes/inc_header.html
{% load staticfiles %}

<nav class="navbar navbar-expand-lg menu p-3">
  <a class="navbar-brand" href="{% url 'main:index' %}">
    GEEKPLANNER
  </a>
  <ul class="nav navbar-nav mx-auto">
    <li>
      <a href="{% url 'main:index' %}"
         class="nav-link rounded font-weight-bold text-center mx-2 menu__item
          {% if request.resolver_match.url_name == 'index' %}menu__item--active{% endif %}">
        Main
      </a>
    </li>
    <li>
      <a href="{% url 'main:pricing' %}"
         class="nav-link rounded font-weight-bold text-center mx-2 menu__item
         {% if request.resolver_match.url_name == 'pricing' %}menu__item--active{% endif %}">
        Pricing
      </a>
    </li>
    <li>
      <a class="nav-link rounded font-weight-bold text-center mx-2 menu__item" href="#">
        Features
      </a>
    </li>
    {% if user.is_authenticated %}
      <li>
        <a href="{% url 'planner:projects' %}"
           class="nav-link rounded font-weight-bold text-center mx-2 menu__item
            {% if request.resolver_match.url_name == 'projects' %}menu__item--active{% endif %}">
          Projects
        </a>
      </li>
      {% if user.is_superuser %}
        <a href="{% url 'admin:users' %}"
           class="nav-link rounded font-weight-bold text-center mx-2 menu__item">
          Admin panel
        </a>
      {% endif %}
    {% endif %}
  </ul>
  {% if user.is_authenticated %}
    <div class="btn-group" role="group">
      <a class="btn btn-outline-primary font-weight-bold btn-register" href="{% url 'auth:logout' %}">
        Sing out
      </a>
      <a class="btn btn-outline-primary font-weight-bold btn-register" href="{% url 'auth:edit' %}">
        Profile
      </a>
    </div>
  {% else %}
    <div class="btn-group" role="group">
      <a class="btn btn-outline-primary font-weight-bold btn-register" href="{% url 'auth:login' %}">
        Sign in
      </a>
      <a class="btn btn-outline-primary font-weight-bold btn-register" href="{% url 'auth:django_registration_register' %}">
        Sign up
      </a>
    </div>
  {% endif %}
</nav>